resolver: nightly-2017-06-14
packages:
- .
- hie-apply-refact
- hie-base
- hie-docs-generator
- hie-eg-plugin-async
- hie-example-plugin2
- hie-ghc-mod
- hie-ghc-tree
- hie-hare
- hie-hoogle
- hie-plugin-api
- hie-brittany
#- ./haskell-lsp
- location:
    git: https://github.com/alanz/haskell-lsp.git
    commit: c2cfaf2a5ae8e796d97c51bc20cd8a6b1f3d96d5
  extra-dep: true
- location:
    git: https://github.com/alanz/ghc-dump-tree.git
    commit: 9dbca928ad5507b144f46bb95123a08d24f24808
  extra-dep: true
# - location:
#     git: https://github.com/sol/hspec-jenkins.git
#     commit: cb012b23c4e524dde9ea129b6146dda20a5ca505
#   extra-dep: true
# - ../HaRe
- location:
    git: https://github.com/alanz/HaRe.git
    commit: 10e802b8f074e055f7b4a91e5573e783cfc58993
  extra-dep: true
# - ../../DanielG/ghc-mod
# - ../ghc-mod
- location:
    git: https://github.com/alanz/ghc-mod.git
    commit: f84c9568d426fc3e54c6323cd356d552d4020e5d
  extra-dep: true
- location:
    git: https://github.com/lspitzner/brittany.git
    commit: 134f31e4d18e51a7cd3d5bcaa90af92e70b926ce
  extra-dep: true

extra-deps:
- apply-refact-0.3.0.1
# - apply-refact-0.4.0.0
- butcher-1.1.0.0
- czipwith-1.0.0.0
- data-tree-print-0.1.0.0
- deque-0.2
- monad-memo-0.4.1
- pipes-aeson-0.4.1.8
- pipes-network-0.6.4.1
# - hspec-jenkins-0.1.1
flags:
  haskell-ide-engine:
    pedantic: true
  hie-apply-refact:
    pedantic: true
  hie-base:
    pedantic: true
  hie-docs-generator:
    pedantic: true
  hie-eg-plugin-async:
    pedantic: true
  hie-example-plugin2:
    pedantic: true
  hie-ghc-mod:
    pedantic: true
  hie-ghc-tree:
    pedantic: true
  hie-hare:
    pedantic: true
  hie-hoogle:
    pedantic: true
  hie-plugin-api:
    pedantic: true
  hie-brittany:
    pedantic: true
